local _, addon = ...

addon.DEFAULT_ITEMS = {
  Ingredients = {
    { category = "Herbs", items = {
      { id = 2447,  name = "Peacebloom" },
      { id = 765,   name = "Silverleaf" },
      { id = 2449,  name = "Earthroot" },
      { id = 785,   name = "Mageroyal" },
      { id = 2450,  name = "Briarthorn" },
      { id = 2453,  name = "Bruiseweed" },
      { id = 3355,  name = "Wild Steelbloom" },
      { id = 3369,  name = "Grave Moss" },
      { id = 3356,  name = "Kingsblood" },
      { id = 3357,  name = "Liferoot" },
      { id = 3818,  name = "Fadeleaf" },
      { id = 3821,  name = "Goldthorn" },
      { id = 3358,  name = "Khadgar's Whisker" },
      { id = 3819,  name = "Wintersbite" },
      { id = 4625,  name = "Firebloom" },
      { id = 8831,  name = "Purple Lotus" },
      { id = 8836,  name = "Arthas' Tears" },
      { id = 8838,  name = "Sungrass" },
      { id = 8839,  name = "Blindweed" },
      { id = 8845,  name = "Ghost Mushroom" },
      { id = 8846,  name = "Gromsblood" },
      { id = 13463, name = "Dreamfoil" },
      { id = 13464, name = "Golden Sansam" },
      { id = 13465, name = "Mountain Silversage" },
      { id = 13466, name = "Sorrowmoss" },
      { id = 13467, name = "Icecap" },
      { id = 13468, name = "Black Lotus" },
    }},
    { category = "Ores & Bars", items = {
      { id = 2770,  name = "Copper Ore" },
      { id = 2840,  name = "Copper Bar" },
      { id = 2771,  name = "Tin Ore" },
      { id = 3576,  name = "Tin Bar" },
      { id = 2841,  name = "Bronze Bar" },
      { id = 2772,  name = "Iron Ore" },
      { id = 3575,  name = "Iron Bar" },
      { id = 2776,  name = "Gold Ore" },
      { id = 3577,  name = "Gold Bar" },
      { id = 3858,  name = "Mithril Ore" },
      { id = 3860,  name = "Mithril Bar" },
      { id = 7911,  name = "Truesilver Ore" },
      { id = 6037,  name = "Truesilver Bar" },
      { id = 10620, name = "Thorium Ore" },
      { id = 12359, name = "Thorium Bar" },
      { id = 11370, name = "Dark Iron Ore" },
      { id = 11371, name = "Dark Iron Bar" },
      { id = 12655, name = "Enchanted Thorium Bar" },
      { id = 12360, name = "Arcanite Bar" },
    }},
    { category = "Leather & Hides", items = {
      { id = 2318,  name = "Light Leather" },
      { id = 2319,  name = "Medium Leather" },
      { id = 4234,  name = "Heavy Leather" },
      { id = 4304,  name = "Thick Leather" },
      { id = 8170,  name = "Rugged Leather" },
      { id = 783,   name = "Light Hide" },
      { id = 4232,  name = "Medium Hide" },
      { id = 4235,  name = "Heavy Hide" },
      { id = 8169,  name = "Thick Hide" },
      { id = 8171,  name = "Rugged Hide" },
    }},
    { category = "Cloth", items = {
      { id = 2589,  name = "Linen Cloth" },
      { id = 2592,  name = "Wool Cloth" },
      { id = 4306,  name = "Silk Cloth" },
      { id = 4338,  name = "Mageweave Cloth" },
      { id = 14047, name = "Runecloth" },
      { id = 14256, name = "Felcloth" },
      { id = 14342, name = "Mooncloth" },
    }},
    { category = "Elemental", items = {
      { id = 7078,  name = "Essence of Fire" },
      { id = 7080,  name = "Essence of Water" },
      { id = 7082,  name = "Essence of Air" },
      { id = 7076,  name = "Heart of Fire" },
      { id = 11382, name = "Blood of the Mountain" },
      { id = 12803, name = "Living Essence" },
      { id = 12808, name = "Essence of Undeath" },
    }},
    { category = "Enchanting", items = {
      { id = 10940, name = "Strange Dust" },
      { id = 11083, name = "Soul Dust" },
      { id = 11137, name = "Vision Dust" },
      { id = 11176, name = "Dream Dust" },
      { id = 16204, name = "Illusion Dust" },
      { id = 10938, name = "Lesser Magic Essence" },
      { id = 10939, name = "Greater Magic Essence" },
      { id = 10998, name = "Lesser Astral Essence" },
      { id = 11082, name = "Greater Astral Essence" },
      { id = 11134, name = "Lesser Mystic Essence" },
      { id = 11135, name = "Greater Mystic Essence" },
      { id = 11174, name = "Lesser Nether Essence" },
      { id = 11175, name = "Greater Nether Essence" },
      { id = 16202, name = "Lesser Eternal Essence" },
      { id = 16203, name = "Greater Eternal Essence" },
      { id = 10978, name = "Small Glimmering Shard" },
      { id = 11138, name = "Small Glowing Shard" },
      { id = 11139, name = "Large Glowing Shard" },
      { id = 11177, name = "Small Radiant Shard" },
      { id = 11178, name = "Large Radiant Shard" },
      { id = 14343, name = "Small Brilliant Shard" },
      { id = 14344, name = "Large Brilliant Shard" },
      { id = 20725, name = "Nexus Crystal" },
    }},
  },

  Consumables = {
    { category = "Utility", items = {
      { id = 184937, name = "Chronoboon Displacer" },
    }},
    { category = "Flasks", items = {
      { id = 13510, name = "Flask of the Titans" },
      { id = 13511, name = "Flask of Distilled Wisdom" },
      { id = 13512, name = "Flask of Supreme Power" },
      { id = 13513, name = "Flask of Chromatic Resistance" },
    }},
    { category = "Battle Elixirs", items = {
      { id = 13452, name = "Elixir of the Mongoose" },
      { id = 9187,  name = "Elixir of Greater Agility" },
      { id = 13453, name = "Elixir of Brute Force" },
      { id = 9206,  name = "Elixir of Giants" },
      { id = 17708, name = "Elixir of Frost Power" },
      { id = 21546, name = "Elixir of Greater Firepower" },
      { id = 9264,  name = "Elixir of Shadow Power" },
      { id = 13454, name = "Greater Arcane Elixir" },
    }},
    { category = "Guardian Elixirs", items = {
      { id = 13445, name = "Elixir of Superior Defense" },
      { id = 3389,  name = "Elixir of Defense" },
      { id = 13447, name = "Elixir of the Sages" },
      { id = 9088,  name = "Gift of Arthas" },
    }},
    { category = "Potions", items = {
      { id = 13446, name = "Major Healing Potion" },
      { id = 13444, name = "Major Mana Potion" },
      { id = 13442, name = "Mighty Rage Potion" },
      { id = 13455, name = "Greater Stoneshield Potion" },
      { id = 20007, name = "Mageblood Potion" },
      { id = 20520, name = "Dark Rune" },
      { id = 20008, name = "Living Action Potion" },
      { id = 5634,  name = "Free Action Potion" },
      { id = 9030,  name = "Restorative Potion" },
      { id = 3387,  name = "Limited Invulnerability Potion" },
      { id = 2459,  name = "Swiftness Potion" },
    }},
    { category = "Protection Potions", items = {
      { id = 13457, name = "Greater Fire Protection Potion" },
      { id = 13456, name = "Greater Frost Protection Potion" },
      { id = 13458, name = "Greater Nature Protection Potion" },
      { id = 13459, name = "Greater Shadow Protection Potion" },
      { id = 13461, name = "Greater Arcane Protection Potion" },
      { id = 13460, name = "Greater Holy Protection Potion" },
    }},
    { category = "Food & Drink", items = {
      { id = 20452, name = "Smoked Desert Dumplings" },
      { id = 13931, name = "Nightfin Soup" },
      { id = 13928, name = "Grilled Squid" },
      { id = 18254, name = "Runn Tum Tuber Surprise" },
      { id = 13810, name = "Blessed Sunfruit" },
      { id = 13813, name = "Blessed Sunfruit Juice" },
      { id = 21023, name = "Dirge's Kickin' Chimaerok Chops" },
    }},
    { category = "Zul'Gurub Buffs", items = {
      { id = 12451, name = "R.O.I.D.S." },
      { id = 12455, name = "Ground Scorpok Assay" },
      { id = 12457, name = "Cerebral Cortex Compound" },
      { id = 12458, name = "Gizzard Gum" },
      { id = 12450, name = "Lung Juice Cocktail" },
    }},
    { category = "Weapon Buffs", items = {
      { id = 18262, name = "Elemental Sharpening Stone" },
      { id = 12404, name = "Dense Sharpening Stone" },
      { id = 12643, name = "Dense Weightstone" },
      { id = 20749, name = "Brilliant Wizard Oil" },
      { id = 20748, name = "Brilliant Mana Oil" },
      { id = 23123, name = "Blessed Wizard Oil" },
    }},
    { category = "Bandages", items = {
      { id = 14529, name = "Runecloth Bandage" },
      { id = 14530, name = "Heavy Runecloth Bandage" },
    }},
  },
}
